Repository Iraqi-programmers/My_Libraryes, pull requests merged in 2025-04, with the labels that each got.

#3 Updated IQD_FinancialAnalyzerCard
  IQD UI Library/UserControls/IQD_FinancialAnalyzerCard.xaml.cs
Labels: documentation

#4 Adding IQD_UC_TextBox_PassTextBox to Library User Control
  IQD UI Library/IQD_UI_Library.csproj.user
  IQD UI Library/UserControls/IQD_UC_TextBox_PassTextBox.xaml
  IQD UI Library/UserControls/IQD_UC_TextBox_PassTextBox.xaml.cs
Labels: documentation

#7 Update On Styles Folder And Add New "ResorsDic" File For PasswordBoxStyles
  IQD UI Library/Styles/ButtonStyles.xaml
  IQD UI Library/Styles/ButtonStyles3D.xaml
  IQD UI Library/Styles/ComboBoxStyles.xaml
  IQD UI Library/Styles/PasswordBoxStyle.xaml
  IQD UI Library/Styles/RadioButtonStyles.xaml
  IQD UI Library/Themes/Generic.xaml
Labels: Just Updated

#9 Added new methods
  MyLib_DotNet/DatabaseExecutor/CRUD.cs
  MyLib_DotNet/DatabaseExecutor/CRUD_Accessories/absDatabaseHelper.cs
  MyLib_DotNet/DatabaseExecutor/CRUD_Accessories/clsDatabaseExecutor.cs
Labels: New features

#12 Updated DatabaseExecutor
  MyLib_DotNet/DatabaseExecutor/CRUD.cs
  MyLib_DotNet/DatabaseExecutor/CRUD_Accessories/absDatabaseHelper.cs
  MyLib_DotNet/DatabaseExecutor/CRUD_Accessories/clsDatabaseExecutor.cs
Labels: good first issue
